# Generated by Django 6.0.5 on 2026-05-28 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('code', models.CharField(max_length=40, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IngestionBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_type', models.CharField(choices=[('sap', 'SAP'), ('utility', 'Utility'), ('travel', 'Travel')], max_length=20)),
                ('ingestion_mode', models.CharField(max_length=80)),
                ('source_reference', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('received', 'Received'), ('processed', 'Processed'), ('failed', 'Failed')], default='received', max_length=20)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('failure_count', models.PositiveIntegerField(default=0)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='ingest.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmissionsRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_type', models.CharField(choices=[('sap', 'SAP'), ('utility', 'Utility'), ('travel', 'Travel')], max_length=20)),
                ('source_record_id', models.CharField(max_length=120)),
                ('activity_date', models.DateField()),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('scope', models.CharField(choices=[('scope_1', 'Scope 1'), ('scope_2', 'Scope 2'), ('scope_3', 'Scope 3')], max_length=20)),
                ('category', models.CharField(choices=[('fuel', 'Fuel'), ('procurement', 'Procurement'), ('electricity', 'Electricity'), ('air_travel', 'Air Travel'), ('hotel', 'Hotel'), ('ground_transport', 'Ground Transport')], max_length=40)),
                ('activity_value', models.DecimalField(decimal_places=4, max_digits=14)),
                ('activity_unit_raw', models.CharField(max_length=30)),
                ('normalized_value', models.DecimalField(decimal_places=4, max_digits=14)),
                ('normalized_unit', models.CharField(max_length=20)),
                ('emission_factor', models.DecimalField(decimal_places=6, max_digits=14)),
                ('emission_factor_unit', models.CharField(max_length=60)),
                ('emissions_kgco2e', models.DecimalField(decimal_places=4, max_digits=14)),
                ('suspicious_reason', models.CharField(blank=True, max_length=255)),
                ('review_state', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('locked', 'Locked')], default='pending', max_length=20)),
                ('reviewed_by', models.CharField(blank=True, max_length=120)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('analyst_note', models.TextField(blank=True)),
                ('source_payload', models.JSONField(default=dict)),
                ('was_edited', models.BooleanField(default=False)),
                ('ingestion_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='ingest.ingestionbatch')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='ingest.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'source_type'], name='ingest_emis_tenant__db5543_idx'), models.Index(fields=['tenant', 'review_state'], name='ingest_emis_tenant__1329d2_idx'), models.Index(fields=['tenant', 'scope'], name='ingest_emis_tenant__be204e_idx')],
                'unique_together': {('tenant', 'source_type', 'source_record_id')},
            },
        ),
    ]
